### ISSUE TITLE
VASP Error Outlier

### ISSUE THREAD

**Issue by jerjorg** [msg-byu/kgridGen#13]
Wiley and I got different representative k-points for the orbits when running kgridGen with these parameters:

(all vectors are columns)
lattice vectors 
 [[ 2.986  0.     1.493]
 [ 0.     0.    -4.479]
 [ 0.     2.986  1.493]]

reciprocal lattice vectors 
 [[ 0.3349  0.     -0.    ]
 [ 0.1116  0.1116 -0.2233]
 [ 0.      0.3349 -0.    ]]

atom positions
[0.0, 0.0, 0.0]
[0.33333333, 0.33333333, 0.33333333]
[0.66666667, 0.66666667, 0.66666667]

atom labels
[0, 0, 1]

grid generating vectors 
 [[ 0.0558 -0.0558  0.0558]
 [ 0.0558  0.0558 -0.0558]
 [-0.0558  0.0558  0.0558]]

offset
[0.0, 0.0, 0.0]

When Wiley ran kgridGen he got (weight, k-point in Cartesian coordinates)
1.0 [0. 0. 0.]
8.0 [ 0.056 -0.056  0.056]
4.0 [ 0.112 -0.112  0.112]
2.0 [0.167 0.056 0.167]
4.0 [-0.112  0.    -0.112]
1.0 [ 0.    -0.112  0.   ]
4.0 [ 0.    -0.     0.112]
8.0 [ 0.056  0.056 -0.167]
4.0 [ 0.    -0.112  0.112]

When I ran kgridGen I got (weight, k-point in Cartesian coordinates)
1.0 [0. 0. 0.]
8.0 [ 0.056 -0.056  0.056]
4.0 [ 0.112 -0.112  0.112]
2.0 [0.167 0.056 0.167]
4.0 [ 0.223 -0.     0.223]
1.0 [ 0.    -0.112  0.   ]
4.0 [0.    0.    0.112]
8.0 [ 0.056 -0.056  0.167]
4.0 [ 0.    -0.112  0.112]
The weights of the orbits are the same.

**Comment by glwhart** [comment]
Is this still open?

**Comment by jerjorg** [comment]
Wiley and I got different representative k-points for the orbits but our representative k-points were symmetrically equivalent. We double checked this by verifying that the energy eigenvalues at symmetrically equivalent k-points were the same.
