### ISSUE TITLE
Incorrect orbits determined for BCC lattice

### ISSUE THREAD

**Issue by KaceyLeavitt** [msg-byu/kgridGen#2]
For HNF of [[1, 0, 0], [2, 3, 0], [4, 5, 6]], reciprocal lattice vectors of [[-1, 1, -1], [1, -1, -1], [-1, -1, 1]], and shift of [0, 0, 0], the code gives the incorrect weights for each orbit.

**Comment by glwhart** [comment]
How do you know that they are incorrect? And if so, what's going wrong, do you think?

**Comment by KaceyLeavitt** [comment]
The code placed the k-point [1/9, -5/9, -1/9] in an orbit with weight 1 when it should also have the k-point [-1/9, 13/9, 1/9] in its orbit. The code also placed the k-point [-.5, -.5, .5] in an orbital of weight two, but that k-point should be in an orbital of weight 1. I think this problem stems from an issue with indices in the hashtable.

**Comment by KaceyLeavitt** [comment]
By making a slight change to the hashtable indexing, the issue was fixed and the unit test is now passing.

**Comment by glwhart** [comment]
Did you commit the change to master?

Can you be specific about what was wrong with the indexing and how you changed it? We need to be more verbose...

**Comment by jerjorg** [comment]
It was committed in revision 0.2.6. Here is the line of code that changed
```
! iFirst(cOrbit) = idx
iFirst(cOrbit) = iUnRdKpt
```
Instead of having iFirst point from cOrbit to the index of a k-point that represented the orbit, it was changed so that cOrbit pointed to the position of the representative k-point in UnreducedKpList.

**Comment by glwhart** [comment]
Great. I see what the problem was now. Thanks
