### ISSUE TITLE
Consistent equality checks between subroutines.

### ISSUE THREAD

**Issue by wsmorgan** [msg-byu/kgridGen#3]
In ```generateKpoints.f90``` the subroutine ```generateFullKpointList``` uses the following to check that "The point generating vectors and the reciprocal lattice are incommensurate.":

```
    if (any(matmul(Kinv,R) -  nint(matmul(Kinv,R)) > eps)) then
```

in the subroutine ```symmetryReduceKpointList``` The following check is run instead:

```
    if (.not. equal(matmul(InvK,R), nint(matmul(InvK,R)), eps)) then
```
These two look equivalent on the surface but for some reason they aren't. I've just built a grid that passes the check in ```generateFullKpointList``` but not the one in ```symmetryReduceKpointList```. The grid in question has a reciprocal lattice of:
```
1 0 0
0 0.5 -0.5
0 0.5 0.5
```
and the point generating vectors are:
```
1 0 0
0 0.5 -0.5
-0.5 -0.249953 0.250047
```
it was generated from an HNF of:
```
1 0 0
0 1 0
5324 5324 10648
```
I suggest that the first equality check be used since it's correctly recognizing that the grid and the cell are commensurate.

**Comment by wsmorgan** [comment]
Also you have the same check repeated twice in the ```generateFullKpointList``` subroutine just fyi.

**Comment by glwhart** [comment]
The ".not. equal.." check is better than the "any(...) > eps" since the latter will not do what you want when the ... is bigger than eps *but negative*. I've changed it in my local copy and will push it to the master branch.

I don't see the same check repeated in ```generateFullKpointList```

**Comment by wsmorgan** [comment]
On lines 96 to 109 you have: 
```
    if (any(matmul(Kinv,R) -  nint(matmul(Kinv,R)) > eps)) then
       write(*,*) "ERROR: (generateFullKpointList in generateKpoints.f90):"
       stop "The point generating vectors and the reciprocal lattice are incommensurate."
    endif
    call matrix_inverse(R,Rinv,err)
        if (err) then
       write(*,*) "ERROR: (generateFullKpointList in generateKpoints.f90):"
       write(*,*) "The reciprocal lattice vectors are linearly dependent."
       stop
    endif
    if (any(matmul(Kinv,R) -  nint(matmul(Kinv,R)) > eps)) then
       write(*,*) "ERROR: (generateFullKpointList in generateKpoints.f90):"
       stop "The point generating vectors and the reciprocal lattice are incommensurate."
    endif
```

The first and last if statements in this code block are identical.

**Comment by glwhart** [comment]
I see it now. Thanks. I've removed the duplicate lines and will include the changes in my next revision.
