### ISSUE TITLE
Bug in python wrapper?

### ISSUE THREAD

**Issue by cajfisher** [msg-byu/kgridGen#30]
The python wrapper is giving the following error:

f90wrap_kpointgeneration.f90:31:31:

   31 |         reps_=reps_, aeps_=aeps)
      |                               1
Error: Symbol ‘aeps’ at (1) has no IMPLICIT type; did you mean ‘aeps_’?

Changing line 31 in  wrap/f90wrap_kpointgeneration.f90 from "aeps_=aeps" to "aeps_=aeps_" to match with src/kpointgeneration.f90 should fix it.

**Comment by glwhart** [comment]
Thanks @cajfisher . I've updated the repo now.
