### ISSUE TITLE
Eliminating the search within a sphere when mapping points to first Brillouin zone

### ISSUE THREAD

**Issue by jerjorg** [msg-byu/kgridGen#5]
We made changes to the routine that maps points into the first Brillouin zone and we wanted to have a place where we could record our thoughts for future reference and just in case our changes break something.

The following is taken from Gus's notes and describes how the routine originally was implemented.

> For efficiency's sake, first do a Minkowski reduction on the reciprocal vectors (R) to get the most compact cell possible. This will limit the search over possible translations to the smallest set possible. For each k-point, check each equivalent translation and select the one that is closest to the origin. By definition, the closest point is the translationally equivalent "brother" that is in the first Brillioun zone.

We removed the search over translationally equivalent k-points by mapping the k-points into the first unit cell of the Minkowski basis. Instead of searching for translationally equivalent k-points within a sphere, the search is restricted to the eight unit cells that have a vertex at the origin. The Minkowski basis assures that we don't run into problems like the one shown in the picture below where there are points closer to the origin than those that lie within the eight unit cells that have a vertex at the origin (four unit cells in 2D).

<img width="448" alt="screen shot 2017-08-18 at 2 57 22 pm" src="https://user-images.githubusercontent.com/8594875/29477430-a96ca3f4-8425-11e7-9ea1-a04e3f05c19a.png">

**Comment by glwhart** [comment]
I'd still like to be sure that the eight "octant" search has no exceptions, but I don't know how to prove it. In any case, if we have unit tests of all different lattice types and aspect ratios that should make the approach robust, even if we have a formal proof.
